### ISSUE TITLE
`Publish-BicepNetFile` does not log error or success

### ISSUE THREAD

**Issue by PalmEmanuel** [PSBicep/BicepNet#32]
**Describe the bug**
The command `Publish-BicepNetFile` does not throw errors or log information on success, meaning that it's quite tricky to figure out if it went well.

**Comment by StefanIvemo** [comment]
What can we do here? `bicep publish` does not log anything on success. It should throw an error though if something is wrong with my credentials.

**Comment by PalmEmanuel** [comment]
What mainly caused me to open the issue was that when testing different credentials, there was no way to see if the credential was invalid or not. A verbose message could be useful I think, or at least an error if it didn't go through.

**Comment by jambar42** [comment]
This may be related to [Publish-Bicep should throw failure on module publishing failure.](https://github.com/PSBicep/PSBicep/issues/276) as well. The behavior between bicep and Publish-Bicep is different on intentional publish failure conditions.

**Comment by PalmEmanuel** [comment]
This was solved in #45 by @SimonWahlin implementing better async/await handling of the internal methods. We now properly throw the error to the user. It will be fixed in the next version of the PSBicep module, also then closing https://github.com/PSBicep/PSBicep/issues/276. Good find @jambar42!
