### ISSUE TITLE
Add support for external plaintext access tokens

### ISSUE THREAD

**Issue by PalmEmanuel** [PSBicep/BicepNet#33]
**Describe the solution you'd like**
I'd like to be able to use an existing access token retrieved from an external source, such as the `AzAuth` module, Az CLI or Az PowerShell module, but as plaintext.

A token parameter should be provided for each BicepNet command that has anything to do with authentication.

**Comment by PalmEmanuel** [comment]
Working on a `Set-BicepNetCredential` command instead of providing a `-Token` on all relevant commands.

**Comment by SimonWahlin** [comment]
Fixed in #49
