### ISSUE TITLE
path error in Build-BicepNet

### ISSUE THREAD

**Issue by bjompen** [PSBicep/BicepNet#46]
**Describe the bug**

When running `Build-Bicep` on a bicep file where the path contains a HTML encoded character it throws a "path not found" error, and interprets the characters wrong. This also creates the unexpected behaviour of being able to build bicep files from the wrong directory.

![image](https://user-images.githubusercontent.com/17783007/189853308-bdf972a8-8c3c-4fb4-bdae-bb33de71e3b4.png)

**To Reproduce**

1. Create a folder with the characters `%20` somewhere in the path
2. Add a bicep file to this folder
3. run `Build-Bicep -Path .\bicepFile.bicep`

Bonus weirdness verification:
1. Create a folder with the characters `%20` somewhere in the path, for example `.\My%20Path\`
2. Create a folder with the same name, but space instead of `%20`, for example `.\My Path\`
3. Add the same bicep file in both folders
4. run `Build-Bicep -Path .\bicepFile.bicep`
 
 This builds the file from the wrong folder!

**Reason**

This most likely comes from bicep internally interpreting paths as URI, and therefore interprets paths wrong.

**Expected behavior**

if path is _not_ a web URI it should not interpret web characters.

**Comment by SimonWahlin** [comment]
Good news! 
You fixed it upstream (https://github.com/Azure/bicep/pull/8418) and I can confirm that it will work in BicepNet.PS as well as PSBicep after next bicep release.
